From docker.elastic.co/elasticsearch/elasticsearch:6.1.2
run bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.1.2/elasticsearch-analysis-ik-6.1.2.zip

