version: '2'
services:
  mysql-master:
    image: mysql:5.7
    ports:
      - 33072:3306
    volumes:
      - $PWD/master:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  mysql-slave0:
    image: mysql:5.7
    ports:
      - 33073:3306
    volumes:
      - $PWD/slave:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
