version: '2'
services:
  kanboard:
    image: 192.168.1.62:18443/kanboard/kanboard:latest
    ports:
     - "8082:80"
     - "18443:443"
    volumes:
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl
     - ./config.php:/var/www/app/config.php
    environment :
     - DATABASE_URL=mysql://root:sa@192.168.1.25:3306/kanboard
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local

