From docker.elastic.co/elasticsearch/elasticsearch:6.2.3
ADD elasticsearch-analysis-ik-6.2.3.zip ./
run bin/elasticsearch-plugin install  file:///usr/share/elasticsearch/elasticsearch-analysis-ik-6.2.3.zip 
