version: '2'

services:
  postgresql-server:
    image : postgres:9.5
    ports :
     - 5432:5432
    volumes:
     - ocdb-data:/var/lib/postgresql/data
     - $PWD/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: always
    environment:
     - POSTGRES_INITDB_ARGS=-E 'UTF-8' --locale=POSIX
     - POSTGRES_PASSWORD=postgres123

  openclinica-server:
    image: piegsaj/openclinica
    ports:
      - 8000:8000
    volumes:
      - oc-data:/usr/local/tomcat/openclinica.data
    restart: always
    depends_on:
      - postgresql-server
    environment:
      - LOG_LEVEL=INFO
      - TZ=UTC-1
      - DB_TYPE=postgres
      - DB_HOST=postgresql-server
      - DB_NAME=openclinica
      - DB_USER=clinica
      - DB_PASS=clinica
      - DB_PORT=5432
volumes:
   ocdb-data :
      driver : local
   oc-data :
      driver : local